package com.drivon.api.fuel;

import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;
import org.jspecify.annotations.Nullable;

/**
 * Body for logging or replacing a fill-up. Decimals may be sent as strings or numbers.
 *
 * @param id optional ID generated by the app for an offline draft; resending the same ID returns
 *     the record already saved instead of a duplicate. Ignored on update.
 * @param pricePerLitre optional; calculated from amount and litres when left out, otherwise it must
 *     agree with them to within 1% (or Rs. 1)
 */
public record FuelRecordRequest(
    @Nullable UUID id,
    @NotNull LocalDate date,
    @NotNull @DecimalMin("0.001") @DecimalMax("999.999") @Digits(integer = 3, fraction = 3) BigDecimal litres,
    @NotNull @DecimalMin("0.01") @DecimalMax("9999999.99") @Digits(integer = 7, fraction = 2) BigDecimal amount,
    @DecimalMin("0.01") @DecimalMax("99999.99") @Digits(integer = 5, fraction = 2) @Nullable BigDecimal pricePerLitre,
    @NotNull @Min(0) @Max(2_000_000) Integer odometerKm,
    @NotNull Boolean fullTank,
    @Size(max = 100) @Nullable String station) {}
