-- Fill-ups. IDs may be generated by the app (offline drafts), so they are not
-- defaulted here. Each fill-up's odometer also sits on the vehicle's odometer
-- timeline (odometer_readings, source FUEL). Efficiency (km/L) is calculated
-- from these rows on demand, never stored. See docs/adr/0008-fuel-records.md.
CREATE TABLE fuel_records (
    id              UUID PRIMARY KEY,
    vehicle_id      UUID           NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    filled_on       DATE           NOT NULL,
    litres          NUMERIC(7, 3)  NOT NULL CHECK (litres > 0),
    amount          NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    price_per_litre NUMERIC(10, 2) NOT NULL CHECK (price_per_litre > 0),
    odometer_km     INTEGER        NOT NULL CHECK (odometer_km BETWEEN 0 AND 2000000),
    full_tank       BOOLEAN        NOT NULL,
    station         VARCHAR(100),
    created_at      TIMESTAMPTZ    NOT NULL,
    updated_at      TIMESTAMPTZ    NOT NULL
);

-- Serves per-vehicle history (newest first) and date-range totals.
CREATE INDEX idx_fuel_records_vehicle_filled_on ON fuel_records (vehicle_id, filled_on);
