package com.drivon.api.assistant.llm;

import tools.jackson.databind.JsonNode;

/**
 * A model's request to run a tool.
 *
 * @param id identifies the call so its result can be matched to it; generated by the client when
 *     the provider doesn't send one (see {@link #GENERATED_ID_PREFIX})
 * @param arguments the arguments the model chose, as a JSON object; never trusted as-is
 */
public record ToolCall(String id, String name, JsonNode arguments) {

  /** Prefix of IDs made up by the client rather than the provider. */
  public static final String GENERATED_ID_PREFIX = "drivon-call-";

  public boolean hasGeneratedId() {
    return id.startsWith(GENERATED_ID_PREFIX);
  }
}
